### PR TITLE
Fixes archive links with ' in their href

### PR DESCRIPTION
**Pull request by fcoskar**
Examples:
https://supinic.com/track/detail/9
https://supinic.com/track/detail/79

### CODE REVIEW

**Comment by Supinic** [comment]
Looks good, will merge - but into the future I'd like to have a solution that's proofed against links that contain quote marks `"` as well

**Comment by fcoskar** [comment]
You can do that by replacing `"` with `&quot;`
Example:
```js
const url = `link with " in it`
const format = str => str.replace(/"/g, '&quot;')
console.log(`<a href="${format(url)}"></a>`)
```
[MDN](https://developer.mozilla.org/en-US/docs/Glossary/Entity)

**Comment by fcoskar** [comment]
Have a look at [URL's](https://developer.mozilla.org/en-US/docs/Web/API/URL#Usage_notes) usage notes.
Example with https://supinic.com/track/detail/2806:
```js
const link = `https://gachiarchive.ivr.fi/Pigeon John - "The Bomb" (right♂version)_e9NrA-u_Kko.mp3`
const a = document.createElement('a')
a.innerHTML = `<a href="${new URL(link)}">Test</a>`
console.log(a.innerHTML) // <a href="https://gachiarchive.ivr.fi/Pigeon%20John%20-%20%22The%20Bomb%22%20(right%E2%99%82version)_e9NrA-u_Kko.mp3">Test</a>
```

**Comment by oska1204** [comment]
You can change ' to %27 in the href.
So you could reverse the change.

Example:
https://gachiarchive.ivr.fi/%E2%99%82%20Counting%20AAAAA%27s%20%E2%99%82_SGLkRKAkXxQ.mp3
Original:
https://gachiarchive.ivr.fi/%E2%99%82%20Counting%20AAAAA's%20%E2%99%82_SGLkRKAkXxQ.mp3

**Pull request merged**
