### PR TITLE
Fixes and stuff for supinic.com "forking"

### PR DESCRIPTION
**Pull request by EuleHaken**

### CODE REVIEW

**Comment by EuleHaken** [comment]
So, as far as is see, we need those (config) variables which are needed in those files:

- supibot-package-manager/got/global/index.mjs
  - DEFAULT_USER_AGENT
- supibot-package-manager/got/helix/index.mjs
  - TWITCH_CLIENT_ID
  - TWITCH_APP_ACCESS_TOKEN
- supibot-package-manager/got/vimeo/index.mjs
  - VIMEO_API_KEY
- supi-core/classes/user.js
  - LOG_USER_CRON
- supibot-package-manager/crons/yoink-soundcloud-client-id/index.js
  - SOUNDCLOUD_CLIENT_ID

Most of those could probably just be set up using default values like "" or whatever.

After setting up those variables, at least you are able to connect to the main website. However, most (or all, idk) endpoints dont really work.

E.g.: I think every endpoint throws this (atleast for me):
```
GotError: connect ETIMEDOUT (ip/url):80
    at onError (node_modules\got\dist\source\request-as-event-emitter.js:140:29)
    at handleRequest (node_modules\got\dist\source\request-as-event-emitter.js:173:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```
(Couldn't get any better stack traces, sorry)

**Comment by EuleHaken** [comment]
There are also some hardcoded values containing supinics values, like TwitchID or Twitch Username.

Maybe, during a setup, we could ask for those values, set them up into the database, maybe in Config table, and then use those.

**Comment by EuleHaken** [comment]
So, as far as I can tell, it should work now.

However, the `ETIMEDOUT` GotError still remains.

The database setup should still work though - not sure if we wanna keep the "REPLACE_ME" as a default value though..


Also another thing: of course all the images, like the little ppL or pepeL on the main website, won't be shown/loaded as they are in the /public folder, which is not in this repo - Not a big issue though IMO

**Comment by EuleHaken** [comment]
@Supinic the `/data/faq/list` route requires the `data.FAQ` table to exist. Could you add this table (the table definition SQL file) into the `supi-db-init` repo? (Assuming that its not a private thing or so)

**Comment by EuleHaken** [comment]
Those routes need those tables to work:

- /data/faq/list
  - data.FAQ
- /data/origin/list
  - data.Origin
- /bot/poll/list
  - chat_data.Poll_Vote
- /data/changelog/list
  - data.Changelog
- /data/suggestion/stats
  - data.Suggestion

The `Make-a-bot` thing is missing the whole `bot_data` table

Same goes for `Music` and so on.. I won't list all here now.

Maybe we could check if those tables exist and if they do, load everything like normal and if they don't exists, just return with a 404 Not found. Same like [here](https://github.com/Supinic/supinic.com/commit/55ab6f1ac1cdad342626b3d9ab9c0ad56ef893ef)

**Comment by EuleHaken** [comment]
Also, for routes like `/bot/channel/list` or `/bot/stats` we will get a 500 error, because the api will return null.

E.g.:
In `/supinic.com/routes/bot/stats.js` we do this:
```
const { data } = await sb.Got("Supinic", "bot/stats").json();
// data will be null
```

then we do this: 
```
for (const [topKey, topValue] of Object.entries(data)) {}
// Here we get this error: "Cannot convert undefined or null to object"
```

So for those routes, we should check if the response is null and if so, just show something like "No data available". Same as you would do at https://supinic.com/bot/reminder/list when the user has no active reminders - you just show "No data available in table".

**Review by Supinic — APPROVED** [review]
LGTM

**Pull request merged**
